- conf/application.conf
...and disable it in app-config-base.
This means it's always enabled when running locally (either from sm or sbt) and is always disabled when running in the server environments, unless the app-config-base settings are overridden in app-config-{qa,staging,production}.
> NGC-2682 Enable mobile help to save in application.conf, not service-manager-config

- app/uk/gov/hmrc/mobilehelptosave/config/Base64.scala
- app/uk/gov/hmrc/mobilehelptosave/config/GuiceModule.scala
- it/uk/gov/hmrc/mobilehelptosave/StartupConfigISpec.scala
- test/uk/gov/hmrc/mobilehelptosave/config/Base64Spec.scala
The deployment tooling does not allow spaces in config properties so to work around this we base64 encode these config properties.
> NGC-3052 Allow spaces to be specified in title & message in app-config-*

- it/uk/gov/hmrc/mobilehelptosave/InvitationNoFilterISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/InvitationSurveyAndWorkingTaxCreditsFilterISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/InvitationSurveyFilterISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/InvitationWorkingTaxCreditsFilterISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/StartupConfigISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/StartupISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/support/AppBuilder.scala
- it/uk/gov/hmrc/mobilehelptosave/support/MongoTestCollections.scala
- it/uk/gov/hmrc/mobilehelptosave/support/WireMockSupport.scala
...not just the repository integration tests.
This means that the integration tests shouldn't touch the non-test collections at all now.
> [NGC-3168][FD] Use collections with test name suffix for all integration tests

- conf/application.conf
...so that account data in response can be tested by mobile-help-to-save-multi-service-integration-tests, which runs services with their default configuration.
> [NGC-3199][FD] Enable account feature flags by default

- build.sbt
I have a hunch that this `retrieveManaged := true` was responsible for library sources not being available in IntellIJ until `sbt updateClassifiers` was done, however haven't been able to prove this as I haven't been able to reproduce the problem.
> [FD] Remove build setting that is redundant according to PLATOPS-1409

- conf/application.conf
needsLogging and needsAuditing both default to true if not specified, see uk.gov.hmrc.play.bootstrap.config.ControllerConfigs.get(controllerName: String).
Also remove unused needsAuth config from other controllers.
> [FD] Turn off unwanted auditing and logging for SandboxController

- build.sbt
This is in line with the latest init-service template.
This is intended to be a refactoring only (no behaviour changes).
> [FD] Make build more consistent by switching to a single project

- app/uk/gov/hmrc/mobilehelptosave/config/GuiceModule.scala
- app/uk/gov/hmrc/mobilehelptosave/repos/DropInvitationsTask.scala
This will run on startup every time the microservice is started, we should remove this code after it has been run in production (although it won't do any harm if it is run multiple times).
> [NGC-3202][FD] Drop invitations data including tax credits cache

- test/uk/gov/hmrc/mobilehelptosave/services/HelpToSaveAccountServiceSpec.scala
Moving the enrolment check logic from HelpToSaveController into HelpToSaveAccountService (NGC-3812) coincidentally fixed the unwanted warnings (NGC-4102). This commit adds a test to help prevent regressions of NGC-4102.
> [NGC-4102][FD] Add test for rewritten warning code

- it/uk/gov/hmrc/mobilehelptosave/stubs/AuthStub.scala
- it/uk/gov/hmrc/mobilehelptosave/stubs/HelpToSaveStub.scala
- it/uk/gov/hmrc/mobilehelptosave/stubs/ServiceLocatorStub.scala
- it/uk/gov/hmrc/mobilehelptosave/support/WireMockSupport.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveConnectorSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/AuthorisedWithIdsSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/UserServiceSpec.scala
There will probably be no Play 2.6 version of the hmrctest library.
Break dependency on hmrctest.
Also upgrade a few other HMRC libs/plugins platform dependencies just to keep up to date (not really Play 2.6-related).
> [FD] Prepare for Play 2.6

- app/uk/gov/hmrc/mobilehelptosave/domain/Target.scala
- app/uk/gov/hmrc/mobilehelptosave/views/definition.scala.txt
- resources/public/api/conf/1.1/application.raml
- resources/public/api/conf/1.1/examples/account.json
- resources/public/api/conf/1.1/examples/accountNotFound.json
- resources/public/api/conf/1.1/examples/shuttering.json
- resources/public/api/conf/1.1/examples/target.json
- resources/public/api/conf/1.1/examples/transactions.json
- resources/public/api/conf/1.1/schemas/account.json
- resources/public/api/conf/1.1/schemas/shuttering.json
- resources/public/api/conf/1.1/schemas/target.json
- resources/public/api/conf/1.1/schemas/transactions.json
This adds RAML documentation for the new savings target endpoints. 1.1 is currently marked as being ALPHA as it is still under discussion and subject to changes.
> [NGC-4157] Added API documentation for v1.1 to support savings targets

- app/uk/gov/hmrc/mobilehelptosave/config/MobileHelpToSaveConfig.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/HelpToSaveController.scala
- conf/application.conf
- it/uk/gov/hmrc/mobilehelptosave/SavingsTargetsISpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/HelpToSaveControllerSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/SandboxControllerSpec.scala
The `setSavingsTarget` controller action now does a lookup to check that an account exists at NS&I for the NINO and will respond with 404 if not (NGC-4159). 
The controller will now also use the value of the `maximumPaidInThisMonth` from the NS&I account to validate the upper bound on the savings target (NGC-4196) so we no longer need to have configuration in this service for the maximum savings, and if it ever changes either globally or for individual accounts then we won't need to change this service to accommodate that.
> [NGC-4195][NGC-4196] 'Set Target' endpoint now checks if there's an account

- resources/public/api/conf/1.0/application.raml
- resources/public/api/conf/1.0/examples/account.json
- resources/public/api/conf/1.0/examples/target.json
- resources/public/api/conf/1.0/schemas/target.json
The API platform team have confirmed that we don't need to go through another api clinic to add the endpoints we want to add. This PR copies the 1.1 changes back to the 1.0 RAML and json schemas.
Once the frontend apps are changed back to using 1.0 then we should raise another ticket to delete the 1.1 RAML.
> [NGC-4209] Backport api 1.1 changes to 1.0

- README.md
- app/uk/gov/hmrc/mobilehelptosave/config/MobileHelpToSaveConfig.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/StartupController.scala
- app/uk/gov/hmrc/mobilehelptosave/domain/StartupResponse.scala
- conf/application.conf
- it/uk/gov/hmrc/mobilehelptosave/StartupConfigISpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/StartupControllerSpec.scala
Post iOS/Android update this is no longer required
> [BL][NGC-3818] Removing the invitationUrl 

- app/uk/gov/hmrc/mobilehelptosave/controllers/AuthorisedWithIds.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/HelpToSaveController.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/StartupController.scala
- project/AppDependencies.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/AuthorisedWithIdsSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/StartupControllerSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/GetAccountSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/GetTransactionsSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/TestSupport.scala
I've upgraded `play-bootstrap-25` to version `4.0.0`. This version deprecates `MdcLoggingExecutionContext` and replaces it with an `ExecutionContext` that can be injected via guice and does the work of carrying the log context through the call stack. See https://confluence.tools.tax.service.gov.uk/x/HYhsC for more details.
> [DC][NGC-4254] Replace deprecated `MdcLoggingExecutionContext`

- app/uk/gov/hmrc/mobilehelptosave/config/MobileHelpToSaveConfig.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/HelpToSaveController.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/IndexedMongoRepo.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/MongoSavingsGoalRepo.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/SavingsGoalRepo.scala
- app/uk/gov/hmrc/mobilehelptosave/services/AccountService.scala
- project/AppDependencies.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/SandboxControllerSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/GetAccountSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/SavingsGoalSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/TestSupport.scala
- test/uk/gov/hmrc/mobilehelptosave/services/HelpToSaveAccountServiceSpec.scala
The main change here is to add a second type parameter to `IndexedMongoRepo` to represent the type of the index field, and change the `set` method appropriately.
In addition, there is some re-factoring of `AccountService` to help with testing.
> Generic indexed repo

- app/uk/gov/hmrc/mobilehelptosave/controllers/HelpToSaveController.scala
- app/uk/gov/hmrc/mobilehelptosave/services/AccountService.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/GetAccountSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/GetTransactionsSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/TestSupport.scala
- test/uk/gov/hmrc/mobilehelptosave/services/SetSavingsGoalSpec.scala
This breaks the dependency from the controller to the repo.
Francis had already put in place some provision for lifting various errors to the value level using `Either` and `ErrorInfo`. This change expands on that, standardises a lot of responses and reduces boilerplate using helper functions.
> Move delete and get events into the `AccountService`

- app/uk/gov/hmrc/mobilehelptosave/controllers/test/TestController.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/SavingsGoalEventRepo.scala
- conf/test.routes
- conf/testOnlyDoNotUseInAppConf.routes
This test-only endpoint is needed for testing so we can call it to ensure we have an empty collection after the tests run.
> Added test-only endpoint to remove savings goal event

- app/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveConnector.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/ControllerChecks.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/HelpToSaveController.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/SandboxController.scala
- app/uk/gov/hmrc/mobilehelptosave/domain/ErrorInfo.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/IndexedMongoRepo.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/SavingsGoalEventRepo.scala
- app/uk/gov/hmrc/mobilehelptosave/services/AccountService.scala
- app/uk/gov/hmrc/mobilehelptosave/services/package.scala
- it/uk/gov/hmrc/mobilehelptosave/SandboxISpec.scala
- test/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveConnectorSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/GetTransactionsSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/TestSupport.scala
- test/uk/gov/hmrc/mobilehelptosave/services/HelpToSaveAccountServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/SetSavingsGoalSpec.scala
I have re-worked the savings goal event collection. Now, rather than storing an object for the nino with a list of events inside it, the collection just stores events. Events already contain the nino, so it's no problem to select events for a given user, and it makes it easy to have mongo sort and return only the latest event when we just want to determine what the current savings goal is.
This PR also includes changes to the transactions api so that rather than signalling no-account by returning an `Right[Option[List[Transaction]]]`, the call will return `Right[List[Transaction]]` if the account exists and `Left(AccountNotFound)` if it doesn't, to be consistent with other calls (apart from the `account` call, which I've yet to convert) and then the standard error handling in the …
> [DC] Rework events collection

- app/uk/gov/hmrc/mobilehelptosave/wiring/ServiceComponents.scala
- conf/health2.routes
- conf/prod.routes
- it/uk/gov/hmrc/mobilehelptosave/SandboxISpec.scala
When I originally did the static wiring for the components there was a problem with the version of the health routes from the play 2.5 version of the `play-health` library. Because it had been built with the static routes compiler, the `health.Routes` class was using the guice injector to wire things, which was not compatible with the static DI, so I added a `health2.routes` file that replicated the routes using the non-static routes compiler.
Now that we've upgraded to Play 2.6, we're using a version of `play-health` that has a non-statically-compiled routes file (i.e. `health.Routes` is now a class that takes its dependencies as parameters) so I have removed the work-around `health2.routes` file and updated the `prod.routes`.
> [DC] Remove workaround `health2.routes`

- resources/public/api/conf/1.0/application.raml
The mobile-help-to-save and help-to-same both have the title in the RAML defined as "Help to save". This is causing some confusion on the API Platform / API Catalogue where we're using the title, and it looks like we have two copies of the Help To Save API!
So this is to rename this one to include Mobile in the RAML title.
> API-4942 - Tweaked RAML title
