- README.md
- app/uk/gov/hmrc/mobilehelptosave/config/GuiceModule.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/StartupController.scala
- app/uk/gov/hmrc/mobilehelptosave/model/StartupResponse.scala
- conf/app.routes
- conf/application.conf
- it/uk/gov/hmrc/DELETEME
- it/uk/gov/hmrc/mobilehelptosave/controllers/StartupISpec.scala
- project/AppDependencies.scala
No unit tests for `StartupController` for the time being because it is mainly wiring so the integration test is more important. Planning to add unit tests for it if/when it gets more logic - or if others think they are needed now?
> NGC-2662 Add startup endpoint

- conf/application-json-logger.xml
- conf/application.conf
This is similar to the changes already done in [native-app-widget](https://github.com/hmrc/native-app-widget/commit/c5e40e1d3ffb4200eb20d50884d4942f246ed35b).
> Fix warnings about deprecated configuration

- app/uk/gov/hmrc/mobilehelptosave/config/GuiceModule.scala
- app/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveConnector.scala
- app/uk/gov/hmrc/mobilehelptosave/connectors/NativeAppWidgetConnector.scala
- app/uk/gov/hmrc/mobilehelptosave/services/SurveyService.scala
- app/uk/gov/hmrc/play/encoding/UriPathEncoding.scala
- conf/application.conf
- it/uk/gov/hmrc/mobilehelptosave/controllers/StartupConfigISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/controllers/StartupISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/stubs/NativeAppWidgetStub.scala
- it/uk/gov/hmrc/mobilehelptosave/support/WireMockSupport.scala
- it/uk/gov/hmrc/play/encoding/UriPathEncodingSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveConnectorSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/connectors/NativeAppWidgetConnectorSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/SurveyServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/support/FakeHttpGet.scala
- test/uk/gov/hmrc/mobilehelptosave/support/ThrowableWithMessageContaining.scala
Return user.state = `InvitedFirstTime` when user is not already enrolled and has indicated that they wanted to be contacted.
Distinguishing first time from other times and returning `Invited` instead of `InvitedFirstTime` is still to do.
> NGC-2682 part 2

- README.md
...so that they will be accepted by web-session which only accepts relative URLs in production environments.
NGC-2741 NGC-2742 NGC-2732 NGC-2733
> invitationUrl and accessAccountUrl should not be resolved in context

- README.md
As discussed in Slack, here is a first go at the JSON for further HtS work.
> JSON to support balance, paid in this month and first bonus stories.

- README.md
Small tweaks to JSON and comments.
> README update after discussion

- README.md
> firstBonusFromDate

- app/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveProxyConnector.scala
- app/uk/gov/hmrc/mobilehelptosave/domain/Account.scala
- app/uk/gov/hmrc/mobilehelptosave/services/AccountService.scala
- build.sbt
- it/uk/gov/hmrc/mobilehelptosave/StartupISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/stubs/HelpToSaveProxyStub.scala
- project/AppDependencies.scala
- test/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveProxyConnectorSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/AccountServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/UserServiceSpec.scala
Also improve error handling when bad JSON is returned by NS&I, this affects NGC-2773 as well.
> NGC-2783 Add bonus info to startup response

- README.md
- app/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveProxyConnector.scala
- app/uk/gov/hmrc/mobilehelptosave/domain/Account.scala
- app/uk/gov/hmrc/mobilehelptosave/services/AccountService.scala
- it/uk/gov/hmrc/mobilehelptosave/StartupISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/stubs/HelpToSaveProxyStub.scala
- project/build.properties
- project/plugins.sbt
- test/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveProxyConnectorSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/AccountServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/UserServiceSpec.scala
Add fields required for:
- NGC-3132 Account closed during first bonus period
- NGC-3062 Ensure month end date always matches paid in amounts
> NGC-3062 NGC-3132 More account fields

- conf/api.routes
- conf/prod.routes
- it/uk/gov/hmrc/mobilehelptosave/TransactionsISpec.scala
- resources/public/api/conf/1.0/application.raml
See individual commit messages for details.
> NGC-3251 Transactions URL changes

- app/uk/gov/hmrc/config/MobileHelpToSaveConfig.scala
- app/uk/gov/hmrc/mobilehelptosave/api/DocumentationController.scala
- app/uk/gov/hmrc/mobilehelptosave/views/definition.scala.txt
- conf/application.conf
- conf/definition.routes
- it/uk/gov/hmrc/mobilehelptosave/api/PlatformIntegrationSpec.scala
Also tidy up some unnecessary JSON in the definition.
> [FD] NGC-3251 Make API private instead of trusted

- app/uk/gov/hmrc/mobilehelptosave/controllers/AuthorisedWithIds.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/AuthorisedWithIdsSpec.scala
To help us prioritise NGC-3381.
> [FD] NGC-3360 Log warning when confidence level check fails

- app/uk/gov/hmrc/mobilehelptosave/api/DocumentationController.scala
- app/uk/gov/hmrc/mobilehelptosave/api/ServiceLocatorRegistrationTask.scala
- app/uk/gov/hmrc/mobilehelptosave/config/EnabledInvitationFilters.scala
- app/uk/gov/hmrc/mobilehelptosave/config/MobileHelpToSaveConfig.scala
- app/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveConnector.scala
- app/uk/gov/hmrc/mobilehelptosave/connectors/TaxCreditsBrokerConnector.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/HelpToSaveController.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/SandboxController.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/StartupController.scala
- app/uk/gov/hmrc/mobilehelptosave/repos/NinoWithoutWtcRepository.scala
- app/uk/gov/hmrc/mobilehelptosave/services/UserService.scala
- conf/application.conf
- it/uk/gov/hmrc/mobilehelptosave/api/ServiceLocatorRegistrationISpec.scala
- test/uk/gov/hmrc/mobilehelptosave/api/DocumentationControllerSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveConnectorSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/connectors/TaxCreditsBrokerConnectorSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/HelpToSaveControllerSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/StartupControllerSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/UserServiceSpec.scala
Don't forget to merge https://github.com/hmrc/app-config-base/pull/439 along with this so that service locator registration continues to be enabled in non-local environments.
> A few cleanups

- app/uk/gov/hmrc/mobilehelptosave/views/definition.scala.txt
See <confluence>/display/DTRG/Identity+Verification+on+the+API+Platform
> [NGC-3679][FD] Specify confidence level so that API platform checks it

- app/uk/gov/hmrc/mobilehelptosave/services/AccountService.scala
- app/uk/gov/hmrc/mobilehelptosave/services/MilestonesService.scala
- it/uk/gov/hmrc/mobilehelptosave/MilestonesISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/stubs/HelpToSaveStub.scala
- test/uk/gov/hmrc/mobilehelptosave/services/MilestonesServiceSpec.scala
- testcommon/uk/gov/hmrc/mobilehelptosave/AccountTestData.scala
Added closed account check to BonusPeriod Milestone logic
Fixed date logic
Fixed date formatting
Updated/added unit tests
> [MR][HMA-1585] QA Fixes

- app/uk/gov/hmrc/mobilehelptosave/domain/MongoMilestone.scala
- app/uk/gov/hmrc/mobilehelptosave/services/BonusPeriodMilestonesService.scala
- it/uk/gov/hmrc/mobilehelptosave/MilestonesISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/stubs/HelpToSaveStub.scala
- test/uk/gov/hmrc/mobilehelptosave/connectors/HelpToSaveConnectorSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/MilestonesServiceSpec.scala
- testcommon/uk/gov/hmrc/mobilehelptosave/AccountTestData.scala
> [HMA-1622] Added new bonusPeriod milestones 

- app/uk/gov/hmrc/mobilehelptosave/domain/MongoMilestone.scala
- app/uk/gov/hmrc/mobilehelptosave/services/AccountService.scala
- app/uk/gov/hmrc/mobilehelptosave/services/BonusPeriodMilestonesService.scala
- it/uk/gov/hmrc/mobilehelptosave/MilestonesISpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/AccountServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/MilestonesServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/SetSavingsGoalSpec.scala
- testcommon/uk/gov/hmrc/mobilehelptosave/AccountTestData.scala
> [HMA-1622] Amended term logic to match previous implementation

- app/uk/gov/hmrc/mobilehelptosave/controllers/HelpToSaveController.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/test/TestController.scala
- app/uk/gov/hmrc/mobilehelptosave/domain/SavingsUpdateResponse.scala
- app/uk/gov/hmrc/mobilehelptosave/domain/TestSavingsGoal.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/SavingsGoalEventRepo.scala
- app/uk/gov/hmrc/mobilehelptosave/services/ReportingService.scala
- app/uk/gov/hmrc/mobilehelptosave/services/SavingsUpdateService.scala
- conf/test.routes
- it/uk/gov/hmrc/mobilehelptosave/SavingsUpdateISpec.scala
- it/uk/gov/hmrc/mobilehelptosave/TestOnlyRoutesISpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/GetAccountSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/GetSavingsUpdateSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/GetTransactionsSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/controllers/helpToSave/TestSupport.scala
- test/uk/gov/hmrc/mobilehelptosave/services/AccountServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/ReportingServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/SavingsUpdateServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/SetSavingsGoalSpec.scala
- testcommon/uk/gov/hmrc/mobilehelptosave/SavingsGoalTestData.scala
- testcommon/uk/gov/hmrc/mobilehelptosave/TransactionTestData.scala
Savings Update - You reach your goal X times
Payload change for savedMonths
Add test-only endpoint for creating savings goals
> [HMA-4100][HMA-4143][HMA-4159] 

- app/uk/gov/hmrc/mobilehelptosave/controllers/HelpToSaveController.scala
- app/uk/gov/hmrc/mobilehelptosave/controllers/test/TestController.scala
- app/uk/gov/hmrc/mobilehelptosave/domain/SavingsUpdateResponse.scala
- app/uk/gov/hmrc/mobilehelptosave/services/CalculatorService.scala
- app/uk/gov/hmrc/mobilehelptosave/services/SavingsUpdateService.scala
- it/uk/gov/hmrc/mobilehelptosave/SavingsUpdateISpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/SavingsUpdateServiceSpec.scala
CurrentGoalName added to goalsReached object in response
> [HMA-4132] Max bonus field added to savings update response

- app/uk/gov/hmrc/mobilehelptosave/services/BonusPeriodMilestonesService.scala
- it/uk/gov/hmrc/mobilehelptosave/MilestonesISpec.scala
Reverts hmrc/mobile-help-to-save#233
> Revert "[HMA-5369] Amend end of Y2 and Y4 milestone dates"

- app/uk/gov/hmrc/mobilehelptosave/config/MobileHelpToSaveConfig.scala
- app/uk/gov/hmrc/mobilehelptosave/domain/MongoMilestone.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/MilestonesRepo.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/PreviousBalanceRepo.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/RunOnStartup.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/SavingsGoalEventRepo.scala
- app/uk/gov/hmrc/mobilehelptosave/repository/SavingsGoalRepoModel.scala
- app/uk/gov/hmrc/mobilehelptosave/services/AccountService.scala
- app/uk/gov/hmrc/mobilehelptosave/services/BalanceMilestonesService.scala
- app/uk/gov/hmrc/mobilehelptosave/services/BonusPeriodMilestonesService.scala
- app/uk/gov/hmrc/mobilehelptosave/services/BonusReachedMilestonesService.scala
- app/uk/gov/hmrc/mobilehelptosave/services/MongoUpdateService.scala
- app/uk/gov/hmrc/mobilehelptosave/wiring/ServiceComponents.scala
- conf/application.conf
- it/uk/gov/hmrc/mobilehelptosave/MilestonesISpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/AccountServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/MilestonesServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/ReportingServiceSpec.scala
- test/uk/gov/hmrc/mobilehelptosave/services/SetSavingsGoalSpec.scala
so that TTL configuration works as expected
> [HMA-6133] Change date field types in mongo from String to Date

- project/AppDependencies.scala
- project/plugins.sbt
> HMA-9802 help to save dependency upgrade
